### ISSUE TITLE
关于全局样式box-sizing: box-box;干扰程序其他部分的样式

### ISSUE THREAD

**Issue by zhaoyunyes** [YanxinNet/uView#410]
版本：1.6.5
### 问题
uView在程序开发的后期引入 并通过@import "uview-ui/index.scss";引入全局样式，但这个全局样式中有box-sizing: box-box;这导致了程序其他部分的样式发生了错乱，而uView的组件又依赖于这个样式，最终导致了无法处理的情况，要不是就是uView的样式错乱 ，要不然就是程序的其他部分样式错乱。如图:
![image](https://user-images.githubusercontent.com/16451550/91812574-ea987980-ec63-11ea-8af0-e0c685de33a4.png)
![image](https://user-images.githubusercontent.com/16451550/91812713-2af7f780-ec64-11ea-98d8-3b7d54406fcf.png)
![image](https://user-images.githubusercontent.com/16451550/91812729-30554200-ec64-11ea-99d2-959ffa737839.png)

### 其他
根据文档[uView组件功能的实现，并不依赖全局样式，内置的一些类名，只是提供一些基础且常用的样式，仅此而已。](http://uviewui.com/components/common.html)
但实际并不是这样
比如tabBar这个组件 依赖于了全局样式.u-border-top，正如依赖了全局的box-sizing: border-box;一样

### 总结
是否可以去掉全局的box-sizing: border-box;?

**Comment by tttao7** [comment]
此问题一致在社区无法拿定，之前删除过，后面社区说不加没法用，加了之后又叫删除。

**Comment by zhaoyunyes** [comment]
```scss
<style lang="scss">
	/* 注意要写在第一行，同时给style标签加入lang="scss"属性 */
	@import "uview-ui/index.scss";
	// 修复box-sizing的问题 https://github.com/YanxinNet/uView/issues/410
	view, text {
		box-sizing: initial;
	}
	
	.u-tabbar {
		view, text {
			box-sizing: border-box;
		}
	}
</style>
```
目前只有这样了。。
