### ISSUE TITLE
Radio组件在微信小程序里图标出现偏移

### ISSUE THREAD

**Issue by zhujinyao822** [YanxinNet/uView#686]
```vue
<u-form-item label="类型" :border-bottom="false">
	<u-radio-group v-model="typeSelect" shape="square">
		<u-radio @change="radioChange" v-for="(item, idx) in typeList" :key="idx" :name="item.value">
			{{item.label}}
		</u-radio>
	</u-radio-group>
</u-form-item>
```

在 h5 端显示正常：
![image](https://user-images.githubusercontent.com/34890562/101244235-2c8ffa80-3740-11eb-8b5d-f402d16f28b1.png)

在微信小程序里：
![image](https://user-images.githubusercontent.com/34890562/101244244-3a458000-3740-11eb-9aaa-cf003183165e.png)

**Comment by zhujinyao822** [comment]
临时解决办法：

```scss
	/* #ifdef MP-WEIXIN */
	// 微信小程序里模态框单选图标样式
	.edit-modal-box ::v-deep .u-icon--right{
		display: block !important;
	}
	/* #endif */
```
