### ISSUE TITLE
SwipeAction内部的元素在display: flex;下的表现与普通html中有区别

### ISSUE THREAD

**Issue by hugselina2019** [YanxinNet/uView#721]
在hbuildx （2.9.8）+ uni-app中
关键代码如下
``` css
.list-item {
  width: 100%;
  height: 84rpx;
  display: flex;
  align-items: center;
  padding: 0 20rpx;
  box-sizing: border-box;
  font-size: 26rpx;
  border-bottom: 1rpx solid #f6f6f6;
  &:nth-child(even) {
    background-color: #f6f6f6;
  }
  .item-img {
    width: 30rpx;
    height: 30rpx;
    margin-right: 20rpx;
  }
  .item-con {
    width: calc(100% - 230rpx);
    // overflow: hidden; 
    // white-space: nowrap;
    // text-overflow: ellipsis;
  }
  .item-time {
    width: 180rpx;
    text-align: right;
    color: #999999;
  }
}
```
然后样式图如下图, 此时u-swiper-content的宽度为 343px
![image](https://user-images.githubusercontent.com/20763416/102678989-32c5b280-41e7-11eb-8424-9b07143efe28.png)

若是打开.item-con 的 white-space: nowrap;属性 会撑开.list-item 如下图 此时u-swiper-content的宽度为 387.16px
``` css
 .item-con {
    width: calc(100% - 230rpx);
    overflow: hidden; 
    white-space: nowrap;
    text-overflow: ellipsis;
  }
```
![image](https://user-images.githubusercontent.com/20763416/102678978-19246b00-41e7-11eb-81c7-cb3dd7cc569a.png)

类似的代码 在vscode  html中没有问题
![image](https://user-images.githubusercontent.com/20763416/102679005-525cdb00-41e7-11eb-8c69-6f47bf846f19.png)

![image](https://user-images.githubusercontent.com/20763416/102679012-58eb5280-41e7-11eb-9ec5-b664d42260a9.png)

请问一下这里有什么坑吗？
