### ISSUE TITLE
自定义tabbar 在ipad 、ipad pro 等大屏设备显示不全

### ISSUE THREAD

**Issue by whypretender** [YanxinNet/uView#779]
![图片](https://user-images.githubusercontent.com/34471419/104428857-ec822a00-55bf-11eb-9cba-2de2429c74d0.png)

**Comment by whypretender** [comment]
![图片](https://user-images.githubusercontent.com/34471419/104429137-3cf98780-55c0-11eb-8dce-c57517f44732.png)

**Comment by auven** [comment]
解决方案是：
- 要么把 `u-tabbar` 的 `height` 设置为 `100` 不带单位的
- 要么将 `u-tabbar` 里面的相关 `rpx` 换成 `px`

我选择了后者，因为那样更贴近原生 tabbar 

App.vue 中
``` scss
.u-tabbar {
  &__content {
    &__item {
      padding: 6px 0 !important;
      &__button {
        top: 6px !important;
        line-height: 1;
      }
      &__text {
        font-size: 12px !important;
        line-height: 14px !important;
        bottom: 6px !important;
      }
    }
  }
}
```
